version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - ./backend/logs:/app/backend/logs
    env_file:
      - ./backend/.env
    restart: always
